api_platform:
    title: Hello API Platform
    version: 1.0.0

    # Swagger Configuration
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    # Defaults Configuration
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 10

    # Supported Formats
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']

    # Additional Configurations
    enable_swagger_ui: true
    enable_re_doc: false
    enable_docs: true
    enable_entrypoint: true

